name: PHPUnit tests automate

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  unit:
    name: PHPUnit tests automate
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Add RSA keys for testing
      run: |
        echo "${{ secrets.PRIVATE_1 }}" > private.pem
        echo "${{ secrets.PRIVATE_2 }}" > private-2.pem
        echo "${{ secrets.PUBLIC_1 }}" > public.pem
        echo "${{ secrets.PUBLIC_2 }}" > public-2.pem

    - name: Creating Autoloader
      uses: php-actions/composer@v6
      with:
        php_version: "7.3"
        dev: yes
        command: dump-autoload

    - name: PHPUnit tests
      uses: php-actions/phpunit@v3
      with:
        php_version: "7.3"
        configuration: "tests/phpunit.xml"
        memory_limit: "256M"
        version: "9.6.11"
